name: Run Notebook Daily

on:
  schedule:
    - cron: '0 5 * * *'  # This schedule runs the workflow daily at 5:00 AM UTC, which is midnight EST
  workflow_dispatch:
  
jobs:
  run_notebook:
    name: Run Jupyter Notebook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install Dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip install openai pandas requests jupyter

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to python vj_gpt_dev.ipynb
          python3 vj_gpt_dev.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Auto-updated notebook execution results" || echo "No changes to commit"
          git push
